/* Generated By:JavaCC: Do not edit this line. DSLParserConstants.java */
package de.uniwue.info2.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DSLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BEGIN_BLOCK_COMMENT = 6;
  /** RegularExpression Id. */
  int AUTHOR_TAG = 9;
  /** RegularExpression Id. */
  int VERSION_TAG = 10;
  /** RegularExpression Id. */
  int DESCRIPTION_TAG = 11;
  /** RegularExpression Id. */
  int OPTIONAL_TAG = 12;
  /** RegularExpression Id. */
  int TAG = 14;
  /** RegularExpression Id. */
  int VARIABLE_NAME = 18;
  /** RegularExpression Id. */
  int SHORT = 19;
  /** RegularExpression Id. */
  int INTEGER = 20;
  /** RegularExpression Id. */
  int LONG = 21;
  /** RegularExpression Id. */
  int DIGITS_INTEGER = 22;
  /** RegularExpression Id. */
  int FLOAT = 23;
  /** RegularExpression Id. */
  int DOUBLE = 24;
  /** RegularExpression Id. */
  int DIGITS_FLOAT = 25;
  /** RegularExpression Id. */
  int BIN_32 = 26;
  /** RegularExpression Id. */
  int BIN_64 = 27;
  /** RegularExpression Id. */
  int HEX_8 = 28;
  /** RegularExpression Id. */
  int HEX_16 = 29;
  /** RegularExpression Id. */
  int BOOL = 30;
  /** RegularExpression Id. */
  int BOOL_TRUE = 31;
  /** RegularExpression Id. */
  int BOOL_FALSE = 32;
  /** RegularExpression Id. */
  int INTERVAL = 33;
  /** RegularExpression Id. */
  int NEGATIVE_INFINITY = 34;
  /** RegularExpression Id. */
  int POSITIVE_INFINITY = 35;
  /** RegularExpression Id. */
  int EMPTY_SET = 36;
  /** RegularExpression Id. */
  int EOL = 37;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int BLOCK_COMMENT = 1;
  /** Lexical state. */
  int TAG_CONTENT = 2;
  /** Lexical state. */
  int VARIABLE = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 4>",
    "\"$\"",
    "\"/*\"",
    "<token of kind 7>",
    "\"*/\"",
    "\"@author\"",
    "\"@version\"",
    "\"@description\"",
    "\"@required\"",
    "\";\"",
    "<TAG>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "<VARIABLE_NAME>",
    "\"short\"",
    "\"int\"",
    "\"long\"",
    "<DIGITS_INTEGER>",
    "\"float\"",
    "\"double\"",
    "<DIGITS_FLOAT>",
    "<BIN_32>",
    "<BIN_64>",
    "<HEX_8>",
    "<HEX_16>",
    "\"bool\"",
    "\"true\"",
    "\"false\"",
    "\"interval\"",
    "\"-inf\"",
    "\"+inf\"",
    "\"empty\"",
    "\";\"",
    "\"pos\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"neg\"",
    "\"add\"",
    "\",\"",
    "\"sub\"",
    "\"mul\"",
    "\"div\"",
    "\"inv\"",
    "\"sqrt\"",
    "\"fma\"",
    "\"interval_case\"",
    "\"median\"",
    "\"is_in\"",
    "\"bisect\"",
    "\":\"",
    "\"<\"",
    "\">\"",
    "\"[\"",
    "\"]\"",
  };

}
